services:
  qdrant:
    image: qdrant/qdrant:v1.4.0
    container_name: qdrant
    ports:
      - "6333:6333"

  ingestion:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ingestion_svc
    ports:
      - "8000:8000"
    environment:
      QDRANT_HOST: qdrant
      QDRANT_PORT: 6333
    depends_on:
      - qdrant
    command: >
      uvicorn microservice_ingestion:app --host 0.0.0.0 --port 8000

  qa:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: qa_svc
    ports:
      - "8001:8000"  # Porta corrigida
    environment:
      QDRANT_HOST: qdrant
      QDRANT_PORT: 6333
    depends_on:
      - qdrant
    command: >
      uvicorn microservice_qa:app --host 0.0.0.0 --port 8000


